### ISSUE TITLE
how to produce BENCHMARK_DISTRIBUTION ?

### ISSUE THREAD

**Issue by nvlong198** [Niger-Volta-LTI/yoruba-text#13]
In dataset_scorer.py, what is BENCHMARK_DISTRIBUTION? and how it can be generated?
thank you.

**Comment by ruohoruotsi** [comment]
@Timilehin do you have any thoughts for @nvlong198?

**Comment by Timilehin** [comment]
Hi @nvlong198 Sorry about the delayed response. BENCHMARK_DISTRIBUTION basically counts the number of occurrences of each character in a huge corpus of quality text and divides this count by the total number of characters. This per character fraction can also be interpreted as a probability distribution and so if we get a new dataset, we can compare to see if certain characters are less frequent than they should be. Hope this makes is clear and please feel free to open a PR that makes the code more understandable.

**Comment by ruohoruotsi** [comment]
Right, so we can say that 2 corpora are similar one way if they have similar distributions of characters (or words).  We should develop this idea of corpora similarity. In the past I've trained a language model from corpus1 (aka LM1) and then computed the "average perplexity" of utterances from corpus2. The lower the perplexity number the more similar the corpora are ...anyway, lots of interesting matters to flesh out here! Thank you for the answer!
