### ISSUE TITLE
Fully scrape the book of mormon

### ISSUE THREAD

**Issue by Timilehin** [Niger-Volta-LTI/yoruba-text#8]
Srape the rest of the book of mormon. 

https://www.lds.org/study/scriptures/dc-testament/title-page?lang=yor

https://www.lds.org/study/scriptures/bofm/title-page?lang=yor

@Timilehin

**Comment by ruohoruotsi** [comment]
Fixed in 4f3ad67119be5a7852f2f31c88cc39e00c8d595b 👍
